### ISSUE TITLE
Getting Following Feeds

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#70]
When I try to get the feeds that the current user is following I get null trying to access the data. If you look at the response from the request it shows there is indeed data but using `value[0].target ` or `value[0]` each returns null.
```
I/flutter (17428): *** Request ***
I/flutter (17428): uri: https://api.stream-io-api.com/api/v1.0/feed/timeline/Prhia3HUNgPesoCjkaEdEUPuOWZ2personal/following?limit=100&offset=0&api_key=hmwext26344q&location=unspecified
I/flutter (17428): method: GET
I/flutter (17428): responseType: ResponseType.json
I/flutter (17428): followRedirects: true
I/flutter (17428): connectTimeout: 10000
I/flutter (17428): sendTimeout: 0
I/flutter (17428): receiveTimeout: 10000
I/flutter (17428): receiveDataWhenStatusError: true
I/flutter (17428): extra: {}
I/flutter (17428): headers:
I/flutter (17428):  stream-auth-type: jwt
I/flutter (17428):  x-stream-client: stream-feed-dart-client-android-0.1.3
I/flutter (17428):  Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiUHJoaWEzSFVOZ1Blc29DamthRWRFVVB1T1daMnBlcnNvbmFsIn0.L8Yu4YxwCb4JykadVwlwTJyidBhIerqGpWn1LAK0Sj4
I/flutter (17428): data:
I/flutter (17428): null
I/flutter (17428):
I/flutter (17428): *** Response ***
I/flutter (17428): uri: https://api.stream-io-api.com/api/v1.0/feed/timeline/Prhia3HUNgPesoCjkaEdEUPuOWZ2personal/following?limit=100&offset=0&api_key=hmwext26344q&location=unspecified
I/flutter (17428): statusCode: 200
I/flutter (17428): headers:
I/flutter (17428):  connection: keep-alive
I/flutter (17428):  cache-control: no-cache
I/flutter (17428):  x-ratelimit-reset: 1621443000
I/flutter (17428):  date: Wed, 19 May 2021 16:49:38 GMT
I/flutter (17428):  access-control-allow-origin: *
I/flutter (17428):  x-ratelimit-limit: 500
I/flutter (17428):  content-encoding: gzip
I/flutter (17428):  x-ratelimit-remaining: 499
I/flutter (17428):  content-type: application/json;charset=utf-8
I/flutter (17428):  access-control-max-age: 86400
I/flutter (17428):  server: nginx
I/flutter (17428):  access-control-allow-headers: x-requested-with, content-type, accept, origin, authorization, x-csrftoken, x-stream-client, stream-auth-type
I/flutter (17428):  access-control-allow-methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
I/flutter (17428):  content-length: 192
I/flutter (17428): Response Text:
I/flutter (17428): {"results":[{"feed_id":"timeline:Prhia3HUNgPesoCjkaEdEUPuOWZ2personal","target_id":"user:WPpmnSSN1uURXNODPak2rlsCV332personal","created_at":"2021-05-14T19:58:27.274792063Z","updated_at":"2021-05-14T19:58:27.274792063Z"}],"duration":"1.62ms"}
I/flutter (17428):
I/flutter (17428): Following: Follow(null, null)
```

**Comment by sachaarbonel** [comment]
Looking at the history it looks like the model got changed. Working on a fix

**Comment by xsahil03x** [comment]
@sachaarbonel in `Follow.dart` add `jsonKey` and regenerate models

```dart
/// The combination of feed slug and user id separated by a colon  
///For example: flat:1  
@JsonKey(name: 'feed_id')
final String? source;

/// the id of the feed you want to follow 
@JsonKey(name: 'target_id')
final String? target;
```

**Comment by rlee1990** [comment]
@sachaarbonel  @xsahil03x thanks will give this a go

**Comment by sachaarbonel** [comment]
hey @rlee1990 the fix landed! can you check it worked:
```yaml
dependencies:   
  stream_feed:
     git:
       url: https://github.com/GetStream/stream-feed-flutter.git
       ref: fix-issue-70
       path: ./packages/stream_feed
```

**Comment by rlee1990** [comment]
Will do right now thanks

**Comment by rlee1990** [comment]
@sachaarbonel It is still not working. I still get the same issue.

**Comment by sachaarbonel** [comment]
did you use the fix branch? https://github.com/GetStream/stream-feed-flutter/issues/70#issuecomment-845127315

**Comment by rlee1990** [comment]
Yes
stream_feed:
     git:
       url: https://github.com/GetStream/stream-feed-flutter.git
       ref: fix-issue-70
       path: ./packages/stream_feed

**Comment by rlee1990** [comment]
My pubspec.lock file output:
```
 stream_feed:
    dependency: "direct main"
    description:
      path: "./packages/stream_feed"
      ref: fix-issue-70
      resolved-ref: "5616ac406830b609d31e4c97357a70dea9198352"
      url: "https://github.com/GetStream/stream-feed-flutter.git"
    source: git
    version: "0.1.3"
```

**Comment by rlee1990** [comment]
@sachaarbonel this is the follow.dart file:
```
import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';

part 'follow.g.dart';

///
@JsonSerializable()
class Follow extends Equatable {
  ///
  const Follow({
    required this.feedId,
    required this.targetId,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Create a new instance from a json
  factory Follow.fromJson(Map<String, dynamic> json) => _$FollowFromJson(json);

  /// The combination of feed slug and user id separated by a colon
  ///For example: flat:1
  final String feedId;

  /// the id of the feed you want to follow
  final String targetId;

  ///Date at which the follow relationship was created
  final DateTime createdAt;

  ///Date at which the follow relationship was updated
  final DateTime updatedAt;

  @override
  List<Object?> get props => [feedId, targetId, createdAt, updatedAt];

  /// Serialize to json
  Map<String, dynamic> toJson() => _$FollowToJson(this);
}
```

**Comment by rlee1990** [comment]
Here is the output:
```
I/flutter (18828): *** Request ***
I/flutter (18828): uri: https://api.stream-io-api.com/api/v1.0/feed/user/Prhia3HUNgPesoCjkaEdEUPuOWZ2personal/followers?limit=100&offset=0&api_key=hmwext26344q&location=unspecified
I/flutter (18828): method: GET
I/flutter (18828): responseType: ResponseType.json
I/flutter (18828): followRedirects: true
I/flutter (18828): connectTimeout: 10000
I/flutter (18828): sendTimeout: 0
I/flutter (18828): receiveTimeout: 10000
I/flutter (18828): receiveDataWhenStatusError: true
I/flutter (18828): extra: {}
I/flutter (18828): headers:
I/flutter (18828):  stream-auth-type: jwt
I/flutter (18828):  x-stream-client: stream-feed-dart-client-android-0.1.3
I/flutter (18828):  Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiUHJoaWEzSFVOZ1Blc29DamthRWRFVVB1T1daMnBlcnNvbmFsIn0.L8Yu4YxwCb4JykadVwlwTJyidBhIerqGpWn1LAK0Sj4
I/flutter (18828): data:
I/flutter (18828): null
I/flutter (18828):
I/flutter (18828): *** Response ***
I/flutter (18828): uri: https://api.stream-io-api.com/api/v1.0/feed/user/Prhia3HUNgPesoCjkaEdEUPuOWZ2personal/followers?limit=100&offset=0&api_key=hmwext26344q&location=unspecified
I/flutter (18828): statusCode: 200
I/flutter (18828): headers:
I/flutter (18828):  connection: keep-alive
I/flutter (18828):  cache-control: no-cache
I/flutter (18828):  x-ratelimit-reset: 1621524420
I/flutter (18828):  date: Thu, 20 May 2021 15:26:10 GMT
I/flutter (18828):  access-control-allow-origin: *
I/flutter (18828):  x-ratelimit-limit: 200
I/flutter (18828):  content-encoding: gzip
I/flutter (18828):  x-ratelimit-remaining: 199
I/flutter (18828):  content-type: application/json;charset=utf-8
I/flutter (18828):  access-control-allow-methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
I/flutter (18828):  content-length: 191
I/flutter (18828): Response Text:
I/flutter (18828): {"results":[{"feed_id":"timeline:WPpmnSSN1uURXNODPak2rlsCV332personal","target_id":"user:Prhia3HUNgPesoCjkaEdEUPuOWZ2personal","created_at":"2021-05-14T20:01:50.119048462Z","updated_at":"2021-05-14T20:01:50.119048462Z"}],"duration":"1.65ms"}
I/flutter (18828):
I/flutter (18828): Follow: {feed_id: timeline:WPpmnSSN1uURXNODPak2rlsCV332personal, target_id: user:Prhia3HUNgPesoCjkaEdEUPuOWZ2personal, created_at: 2021-05-14T20:01:50.119048Z, updated_at: 2021-05-14T20:01:50.119048Z}
E/flutter (18828): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (18828): Receiver: null

```
and the function I ran:
```
 if (widget.isFollowing) {
      widget.streamClient
          .flatFeed("timeline", widget.accountToCheck)
          .following(limit: 100, offset: 0)
          .then((value) {
        print('Follow: ${value[0].toJson()}');
        setState(() {
          data = value;
          isLoading = false;
        });
      });
    } else {
      widget.streamClient
          .flatFeed("user", widget.accountToCheck)
          .followers(limit: 100, offset: 0)
          .then((value) {
        print('Follow: ${value[0].toJson()}');
        setState(() {
          data = value;
          isLoading = false;
        });
      });
    }
```

**Comment by sachaarbonel** [comment]
It's not exactly the same error as you can see the new Follow model correctly parse the HTTP response, so it's not coming from our SDK but your codebase. This works for me when I tried to reproduce
```dart
  final follows =
      await client.flatFeed("timeline").following(limit: 100, offset: 0);
  print(follows[0].toJson());
```

**Comment by rlee1990** [comment]
Sorry I see the new issue now I have to separate the : again thanks the fix is working.

**Comment by sachaarbonel** [comment]
Hey @rlee1990 the fix is now available in v0.2.0 `stream_feed: ^0.2.0` Thanks for your valuable feedback

**Comment by rlee1990** [comment]
Thanks
